


SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE EXTENSION IF NOT EXISTS "pg_graphql" WITH SCHEMA "graphql";






CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";






CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";





SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."addresses" (
    "id" bigint NOT NULL,
    "location_name" character varying(255),
    "maps_url" character varying(255),
    "neighborhood" character varying(255) NOT NULL,
    "number" character varying(255) NOT NULL,
    "street" character varying(255) NOT NULL
);


ALTER TABLE "public"."addresses" OWNER TO "postgres";


ALTER TABLE "public"."addresses" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."addresses_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."bookings" (
    "drive_id" bigint NOT NULL,
    "user_id" bigint NOT NULL,
    "requested_at" timestamp(6) without time zone NOT NULL,
    "role" character varying(20) NOT NULL,
    "status" character varying(20) NOT NULL,
    "updated_at" timestamp(6) without time zone NOT NULL,
    CONSTRAINT "bookings_role_check" CHECK ((("role")::"text" = ANY ((ARRAY['CLIENT'::character varying, 'DRIVER'::character varying])::"text"[]))),
    CONSTRAINT "bookings_status_check" CHECK ((("status")::"text" = ANY ((ARRAY['PENDING'::character varying, 'ACCEPTED'::character varying, 'DECLINED'::character varying, 'CANCELED'::character varying, 'DONE'::character varying])::"text"[])))
);


ALTER TABLE "public"."bookings" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."drives" (
    "id" bigint NOT NULL,
    "available_seats" integer NOT NULL,
    "created_at" timestamp(6) without time zone DEFAULT "now"() NOT NULL,
    "price" numeric(10,2) NOT NULL,
    "time" timestamp(6) without time zone NOT NULL,
    "total_no_seats" integer NOT NULL,
    "from_id" bigint NOT NULL,
    "to_id" bigint NOT NULL,
    "driver_id" bigint,
    "vehicle_id" bigint
);


ALTER TABLE "public"."drives" OWNER TO "postgres";


ALTER TABLE "public"."drives" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."drives_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."faculties" (
    "id" bigint NOT NULL,
    "name" character varying(255),
    "address_id" bigint
);


ALTER TABLE "public"."faculties" OWNER TO "postgres";


CREATE SEQUENCE IF NOT EXISTS "public"."faculties_id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE "public"."faculties_id_seq" OWNER TO "postgres";


ALTER SEQUENCE "public"."faculties_id_seq" OWNED BY "public"."faculties"."id";



CREATE TABLE IF NOT EXISTS "public"."users" (
    "id" bigint NOT NULL,
    "email" character varying(255) NOT NULL,
    "facultyid" bigint,
    "first_name" character varying(255),
    "last_name" character varying(255),
    "password" character varying(255) NOT NULL,
    "phone_number" character varying(255),
    "address_id" bigint,
    "faculty" character varying(255)
);


ALTER TABLE "public"."users" OWNER TO "postgres";


ALTER TABLE "public"."users" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."users_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."vehicles" (
    "id" bigint NOT NULL,
    "vehicle_color" character varying(255),
    "vehicle_licence_plate" character varying(255),
    "vehicle_model" character varying(255),
    "user_id" bigint
);


ALTER TABLE "public"."vehicles" OWNER TO "postgres";


ALTER TABLE "public"."vehicles" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."vehicles_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE ONLY "public"."faculties" ALTER COLUMN "id" SET DEFAULT "nextval"('"public"."faculties_id_seq"'::"regclass");



ALTER TABLE ONLY "public"."addresses"
    ADD CONSTRAINT "addresses_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."bookings"
    ADD CONSTRAINT "bookings_pkey" PRIMARY KEY ("drive_id", "user_id");



ALTER TABLE ONLY "public"."drives"
    ADD CONSTRAINT "drives_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."faculties"
    ADD CONSTRAINT "faculties_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."users"
    ADD CONSTRAINT "uq_users_address_id" UNIQUE ("address_id");



ALTER TABLE ONLY "public"."users"
    ADD CONSTRAINT "uq_users_email" UNIQUE ("email");



ALTER TABLE ONLY "public"."vehicles"
    ADD CONSTRAINT "uq_vehicles_user_id" UNIQUE ("user_id");



ALTER TABLE ONLY "public"."users"
    ADD CONSTRAINT "users_email_key" UNIQUE ("email");



ALTER TABLE ONLY "public"."users"
    ADD CONSTRAINT "users_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."vehicles"
    ADD CONSTRAINT "vehicles_pkey" PRIMARY KEY ("id");



CREATE INDEX "ix_addresses_location_name" ON "public"."addresses" USING "btree" ("location_name");



CREATE INDEX "ix_addresses_neighborhood" ON "public"."addresses" USING "btree" ("neighborhood");



CREATE INDEX "ix_addresses_street_number" ON "public"."addresses" USING "btree" ("street", "number");



CREATE INDEX "ix_bookings_drive_id" ON "public"."bookings" USING "btree" ("drive_id");



CREATE INDEX "ix_bookings_status" ON "public"."bookings" USING "btree" ("status");



CREATE INDEX "ix_bookings_user_id" ON "public"."bookings" USING "btree" ("user_id");



CREATE INDEX "ix_drives_created_at" ON "public"."drives" USING "btree" ("created_at");



CREATE INDEX "ix_drives_driver_id" ON "public"."drives" USING "btree" ("driver_id");



CREATE INDEX "ix_drives_from_id" ON "public"."drives" USING "btree" ("from_id");



CREATE INDEX "ix_drives_from_time" ON "public"."drives" USING "btree" ("from_id", "time");



CREATE INDEX "ix_drives_time" ON "public"."drives" USING "btree" ("time");



CREATE INDEX "ix_drives_to_id" ON "public"."drives" USING "btree" ("to_id");



CREATE INDEX "ix_drives_to_time" ON "public"."drives" USING "btree" ("to_id", "time");



CREATE INDEX "ix_drives_vehicle_id" ON "public"."drives" USING "btree" ("vehicle_id");



CREATE INDEX "ix_users_address_id" ON "public"."users" USING "btree" ("address_id");



CREATE INDEX "ix_vehicles_licence_plate" ON "public"."vehicles" USING "btree" ("vehicle_licence_plate");



CREATE INDEX "ix_vehicles_user_id" ON "public"."vehicles" USING "btree" ("user_id");



ALTER TABLE ONLY "public"."faculties"
    ADD CONSTRAINT "faculties_address_id_fkey" FOREIGN KEY ("address_id") REFERENCES "public"."addresses"("id");



ALTER TABLE ONLY "public"."drives"
    ADD CONSTRAINT "fk6pp70wpr19vi3so2jsym0he0y" FOREIGN KEY ("from_id") REFERENCES "public"."addresses"("id");



ALTER TABLE ONLY "public"."drives"
    ADD CONSTRAINT "fk_drives_driver" FOREIGN KEY ("driver_id") REFERENCES "public"."users"("id");



ALTER TABLE ONLY "public"."drives"
    ADD CONSTRAINT "fk_drives_vehicle" FOREIGN KEY ("vehicle_id") REFERENCES "public"."vehicles"("id");



ALTER TABLE ONLY "public"."users"
    ADD CONSTRAINT "fk_faculty" FOREIGN KEY ("facultyid") REFERENCES "public"."faculties"("id") ON DELETE SET NULL;



ALTER TABLE ONLY "public"."users"
    ADD CONSTRAINT "fke8vydtk7hf0y16bfm558sywbb" FOREIGN KEY ("address_id") REFERENCES "public"."addresses"("id");



ALTER TABLE ONLY "public"."bookings"
    ADD CONSTRAINT "fkeyog2oic85xg7hsu2je2lx3s6" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id");



ALTER TABLE ONLY "public"."drives"
    ADD CONSTRAINT "fko3skd1xrgouwqkun8li5b5lam" FOREIGN KEY ("to_id") REFERENCES "public"."addresses"("id");



ALTER TABLE ONLY "public"."vehicles"
    ADD CONSTRAINT "fko4u5y92lt2sx8y2dc1bb9sewc" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id");



ALTER TABLE ONLY "public"."bookings"
    ADD CONSTRAINT "fkobu3cm83tpdvqc5y0182mrofj" FOREIGN KEY ("drive_id") REFERENCES "public"."drives"("id");





ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";


GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";








































































































































































GRANT ALL ON TABLE "public"."addresses" TO "anon";
GRANT ALL ON TABLE "public"."addresses" TO "authenticated";
GRANT ALL ON TABLE "public"."addresses" TO "service_role";



GRANT ALL ON SEQUENCE "public"."addresses_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."addresses_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."addresses_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."bookings" TO "anon";
GRANT ALL ON TABLE "public"."bookings" TO "authenticated";
GRANT ALL ON TABLE "public"."bookings" TO "service_role";



GRANT ALL ON TABLE "public"."drives" TO "anon";
GRANT ALL ON TABLE "public"."drives" TO "authenticated";
GRANT ALL ON TABLE "public"."drives" TO "service_role";



GRANT ALL ON SEQUENCE "public"."drives_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."drives_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."drives_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."faculties" TO "anon";
GRANT ALL ON TABLE "public"."faculties" TO "authenticated";
GRANT ALL ON TABLE "public"."faculties" TO "service_role";



GRANT ALL ON SEQUENCE "public"."faculties_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."faculties_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."faculties_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."users" TO "anon";
GRANT ALL ON TABLE "public"."users" TO "authenticated";
GRANT ALL ON TABLE "public"."users" TO "service_role";



GRANT ALL ON SEQUENCE "public"."users_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."users_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."users_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."vehicles" TO "anon";
GRANT ALL ON TABLE "public"."vehicles" TO "authenticated";
GRANT ALL ON TABLE "public"."vehicles" TO "service_role";



GRANT ALL ON SEQUENCE "public"."vehicles_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."vehicles_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."vehicles_id_seq" TO "service_role";









ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "service_role";































