plugins {
    id 'java'
}

group = 'campus.ride'
version = '1.0-SNAPSHOT'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

repositories {
    mavenCentral()
}

dependencies {
    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    
    implementation 'org.springframework:spring-context:6.1.0'
    
    implementation 'org.apache.logging.log4j:log4j-api:2.21.1'

    implementation 'org.springframework:spring-context-support:6.1.10'
    implementation 'com.github.ben-manes.caffeine:caffeine:3.1.8'
    implementation 'org.springframework.security:spring-security-crypto:6.3.1'
    implementation("org.springframework.boot:spring-boot-starter-mail:3.5.7")

    implementation project(':Domain')
}

test {
    useJUnitPlatform()
}