spring.application.name=API
spring.datasource.url=jdbc:postgresql://db.dycguxeljfcqbyuctfkw.supabase.co:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=kpXTmWz2AKGR2L7a
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
