spring.application.name=API
spring.datasource.url=jdbc:postgresql://dycguxeljfcqbyuctfkw.supabase.co:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR5Y2d1eGVsamZjcWJ5dWN0Zmt3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE0OTQxNTAsImV4cCI6MjA3NzA3MDE1MH0.Qur3veS_ySKh5MiJ7HUcBxvkTASf4UbpZimBvKKCd9o
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
