plugins {
    id 'java'
}

group = 'campus.ride'
version = '1.0-SNAPSHOT'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(20)
    }
}

repositories {
    mavenCentral()
}

dependencies {

    compileOnly 'jakarta.persistence:jakarta.persistence-api:3.1.0'
    annotationProcessor 'jakarta.persistence:jakarta.persistence-api:3.1.0'

    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    
    implementation 'jakarta.persistence:jakarta.persistence-api:3.1.0'
    implementation 'com.fasterxml.jackson.datatype:jackson-datatype-hibernate6:2.19.2'
    implementation 'org.hibernate.orm:hibernate-core:6.5.3.Final'
}

test {
    useJUnitPlatform()
}