create sequence "public"."faculties_id_seq";


  create table "public"."addresses" (
    "id" bigint generated by default as identity not null,
    "location_name" character varying(255),
    "maps_url" character varying(255),
    "neighborhood" character varying(255) not null,
    "number" character varying(255) not null,
    "street" character varying(255) not null
      );



  create table "public"."bookings" (
    "drive_id" bigint not null,
    "user_id" bigint not null,
    "requested_at" timestamp(6) without time zone not null,
    "role" character varying(20) not null,
    "status" character varying(20) not null,
    "updated_at" timestamp(6) without time zone not null
      );



  create table "public"."drives" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp(6) without time zone not null default now(),
    "price" numeric(10,2) not null,
    "time" timestamp(6) without time zone not null,
    "total_no_seats" integer not null,
    "from_id" bigint not null,
    "to_id" bigint not null
      );



  create table "public"."faculties" (
    "id" bigint not null default nextval('public.faculties_id_seq'::regclass),
    "name" character varying(255),
    "address_id" bigint
      );



  create table "public"."users" (
    "id" bigint generated by default as identity not null,
    "email" character varying(255) not null,
    "facultyid" bigint,
    "first_name" character varying(255),
    "last_name" character varying(255),
    "password" character varying(255) not null,
    "phone_number" character varying(255),
    "address_id" bigint
      );



  create table "public"."vehicles" (
    "id" bigint generated by default as identity not null,
    "vehicle_color" character varying(255),
    "vehicle_licence_plate" character varying(255),
    "vehicle_model" character varying(255),
    "user_id" bigint
      );


alter sequence "public"."faculties_id_seq" owned by "public"."faculties"."id";

CREATE UNIQUE INDEX addresses_pkey ON public.addresses USING btree (id);

CREATE UNIQUE INDEX bookings_pkey ON public.bookings USING btree (drive_id, user_id);

CREATE UNIQUE INDEX drives_pkey ON public.drives USING btree (id);

CREATE UNIQUE INDEX faculties_pkey ON public.faculties USING btree (id);

CREATE INDEX ix_addresses_location_name ON public.addresses USING btree (location_name);

CREATE INDEX ix_addresses_neighborhood ON public.addresses USING btree (neighborhood);

CREATE INDEX ix_addresses_street_number ON public.addresses USING btree (street, number);

CREATE INDEX ix_bookings_drive_id ON public.bookings USING btree (drive_id);

CREATE INDEX ix_bookings_status ON public.bookings USING btree (status);

CREATE INDEX ix_bookings_user_id ON public.bookings USING btree (user_id);

CREATE INDEX ix_drives_created_at ON public.drives USING btree (created_at);

CREATE INDEX ix_drives_from_id ON public.drives USING btree (from_id);

CREATE INDEX ix_drives_from_time ON public.drives USING btree (from_id, "time");

CREATE INDEX ix_drives_time ON public.drives USING btree ("time");

CREATE INDEX ix_drives_to_id ON public.drives USING btree (to_id);

CREATE INDEX ix_drives_to_time ON public.drives USING btree (to_id, "time");

CREATE INDEX ix_users_address_id ON public.users USING btree (address_id);

CREATE INDEX ix_vehicles_licence_plate ON public.vehicles USING btree (vehicle_licence_plate);

CREATE INDEX ix_vehicles_user_id ON public.vehicles USING btree (user_id);

CREATE UNIQUE INDEX uq_users_address_id ON public.users USING btree (address_id);

CREATE UNIQUE INDEX uq_users_email ON public.users USING btree (email);

CREATE UNIQUE INDEX uq_vehicles_user_id ON public.vehicles USING btree (user_id);

CREATE UNIQUE INDEX users_email_key ON public.users USING btree (email);

CREATE UNIQUE INDEX users_pkey ON public.users USING btree (id);

CREATE UNIQUE INDEX vehicles_pkey ON public.vehicles USING btree (id);

alter table "public"."addresses" add constraint "addresses_pkey" PRIMARY KEY using index "addresses_pkey";

alter table "public"."bookings" add constraint "bookings_pkey" PRIMARY KEY using index "bookings_pkey";

alter table "public"."drives" add constraint "drives_pkey" PRIMARY KEY using index "drives_pkey";

alter table "public"."faculties" add constraint "faculties_pkey" PRIMARY KEY using index "faculties_pkey";

alter table "public"."users" add constraint "users_pkey" PRIMARY KEY using index "users_pkey";

alter table "public"."vehicles" add constraint "vehicles_pkey" PRIMARY KEY using index "vehicles_pkey";

alter table "public"."bookings" add constraint "bookings_role_check" CHECK (((role)::text = ANY (ARRAY[('CLIENT'::character varying)::text, ('DRIVER'::character varying)::text]))) not valid;

alter table "public"."bookings" validate constraint "bookings_role_check";

alter table "public"."bookings" add constraint "bookings_status_check" CHECK (((status)::text = ANY (ARRAY[('PENDING'::character varying)::text, ('ACCEPTED'::character varying)::text, ('DECLINED'::character varying)::text, ('CANCELED'::character varying)::text, ('DONE'::character varying)::text]))) not valid;

alter table "public"."bookings" validate constraint "bookings_status_check";

alter table "public"."bookings" add constraint "fkeyog2oic85xg7hsu2je2lx3s6" FOREIGN KEY (user_id) REFERENCES public.users(id) not valid;

alter table "public"."bookings" validate constraint "fkeyog2oic85xg7hsu2je2lx3s6";

alter table "public"."bookings" add constraint "fkobu3cm83tpdvqc5y0182mrofj" FOREIGN KEY (drive_id) REFERENCES public.drives(id) not valid;

alter table "public"."bookings" validate constraint "fkobu3cm83tpdvqc5y0182mrofj";

alter table "public"."drives" add constraint "fk6pp70wpr19vi3so2jsym0he0y" FOREIGN KEY (from_id) REFERENCES public.addresses(id) not valid;

alter table "public"."drives" validate constraint "fk6pp70wpr19vi3so2jsym0he0y";

alter table "public"."drives" add constraint "fko3skd1xrgouwqkun8li5b5lam" FOREIGN KEY (to_id) REFERENCES public.addresses(id) not valid;

alter table "public"."drives" validate constraint "fko3skd1xrgouwqkun8li5b5lam";

alter table "public"."faculties" add constraint "faculties_address_id_fkey" FOREIGN KEY (address_id) REFERENCES public.addresses(id) not valid;

alter table "public"."faculties" validate constraint "faculties_address_id_fkey";

alter table "public"."users" add constraint "fk_faculty" FOREIGN KEY (facultyid) REFERENCES public.faculties(id) ON DELETE SET NULL not valid;

alter table "public"."users" validate constraint "fk_faculty";

alter table "public"."users" add constraint "fke8vydtk7hf0y16bfm558sywbb" FOREIGN KEY (address_id) REFERENCES public.addresses(id) not valid;

alter table "public"."users" validate constraint "fke8vydtk7hf0y16bfm558sywbb";

alter table "public"."users" add constraint "uq_users_address_id" UNIQUE using index "uq_users_address_id";

alter table "public"."users" add constraint "uq_users_email" UNIQUE using index "uq_users_email";

alter table "public"."users" add constraint "users_email_key" UNIQUE using index "users_email_key";

alter table "public"."vehicles" add constraint "fko4u5y92lt2sx8y2dc1bb9sewc" FOREIGN KEY (user_id) REFERENCES public.users(id) not valid;

alter table "public"."vehicles" validate constraint "fko4u5y92lt2sx8y2dc1bb9sewc";

alter table "public"."vehicles" add constraint "uq_vehicles_user_id" UNIQUE using index "uq_vehicles_user_id";

grant delete on table "public"."addresses" to "anon";

grant insert on table "public"."addresses" to "anon";

grant references on table "public"."addresses" to "anon";

grant select on table "public"."addresses" to "anon";

grant trigger on table "public"."addresses" to "anon";

grant truncate on table "public"."addresses" to "anon";

grant update on table "public"."addresses" to "anon";

grant delete on table "public"."addresses" to "authenticated";

grant insert on table "public"."addresses" to "authenticated";

grant references on table "public"."addresses" to "authenticated";

grant select on table "public"."addresses" to "authenticated";

grant trigger on table "public"."addresses" to "authenticated";

grant truncate on table "public"."addresses" to "authenticated";

grant update on table "public"."addresses" to "authenticated";

grant delete on table "public"."addresses" to "service_role";

grant insert on table "public"."addresses" to "service_role";

grant references on table "public"."addresses" to "service_role";

grant select on table "public"."addresses" to "service_role";

grant trigger on table "public"."addresses" to "service_role";

grant truncate on table "public"."addresses" to "service_role";

grant update on table "public"."addresses" to "service_role";

grant delete on table "public"."bookings" to "anon";

grant insert on table "public"."bookings" to "anon";

grant references on table "public"."bookings" to "anon";

grant select on table "public"."bookings" to "anon";

grant trigger on table "public"."bookings" to "anon";

grant truncate on table "public"."bookings" to "anon";

grant update on table "public"."bookings" to "anon";

grant delete on table "public"."bookings" to "authenticated";

grant insert on table "public"."bookings" to "authenticated";

grant references on table "public"."bookings" to "authenticated";

grant select on table "public"."bookings" to "authenticated";

grant trigger on table "public"."bookings" to "authenticated";

grant truncate on table "public"."bookings" to "authenticated";

grant update on table "public"."bookings" to "authenticated";

grant delete on table "public"."bookings" to "service_role";

grant insert on table "public"."bookings" to "service_role";

grant references on table "public"."bookings" to "service_role";

grant select on table "public"."bookings" to "service_role";

grant trigger on table "public"."bookings" to "service_role";

grant truncate on table "public"."bookings" to "service_role";

grant update on table "public"."bookings" to "service_role";

grant delete on table "public"."drives" to "anon";

grant insert on table "public"."drives" to "anon";

grant references on table "public"."drives" to "anon";

grant select on table "public"."drives" to "anon";

grant trigger on table "public"."drives" to "anon";

grant truncate on table "public"."drives" to "anon";

grant update on table "public"."drives" to "anon";

grant delete on table "public"."drives" to "authenticated";

grant insert on table "public"."drives" to "authenticated";

grant references on table "public"."drives" to "authenticated";

grant select on table "public"."drives" to "authenticated";

grant trigger on table "public"."drives" to "authenticated";

grant truncate on table "public"."drives" to "authenticated";

grant update on table "public"."drives" to "authenticated";

grant delete on table "public"."drives" to "service_role";

grant insert on table "public"."drives" to "service_role";

grant references on table "public"."drives" to "service_role";

grant select on table "public"."drives" to "service_role";

grant trigger on table "public"."drives" to "service_role";

grant truncate on table "public"."drives" to "service_role";

grant update on table "public"."drives" to "service_role";

grant delete on table "public"."faculties" to "anon";

grant insert on table "public"."faculties" to "anon";

grant references on table "public"."faculties" to "anon";

grant select on table "public"."faculties" to "anon";

grant trigger on table "public"."faculties" to "anon";

grant truncate on table "public"."faculties" to "anon";

grant update on table "public"."faculties" to "anon";

grant delete on table "public"."faculties" to "authenticated";

grant insert on table "public"."faculties" to "authenticated";

grant references on table "public"."faculties" to "authenticated";

grant select on table "public"."faculties" to "authenticated";

grant trigger on table "public"."faculties" to "authenticated";

grant truncate on table "public"."faculties" to "authenticated";

grant update on table "public"."faculties" to "authenticated";

grant delete on table "public"."faculties" to "service_role";

grant insert on table "public"."faculties" to "service_role";

grant references on table "public"."faculties" to "service_role";

grant select on table "public"."faculties" to "service_role";

grant trigger on table "public"."faculties" to "service_role";

grant truncate on table "public"."faculties" to "service_role";

grant update on table "public"."faculties" to "service_role";

grant delete on table "public"."users" to "anon";

grant insert on table "public"."users" to "anon";

grant references on table "public"."users" to "anon";

grant select on table "public"."users" to "anon";

grant trigger on table "public"."users" to "anon";

grant truncate on table "public"."users" to "anon";

grant update on table "public"."users" to "anon";

grant delete on table "public"."users" to "authenticated";

grant insert on table "public"."users" to "authenticated";

grant references on table "public"."users" to "authenticated";

grant select on table "public"."users" to "authenticated";

grant trigger on table "public"."users" to "authenticated";

grant truncate on table "public"."users" to "authenticated";

grant update on table "public"."users" to "authenticated";

grant delete on table "public"."users" to "service_role";

grant insert on table "public"."users" to "service_role";

grant references on table "public"."users" to "service_role";

grant select on table "public"."users" to "service_role";

grant trigger on table "public"."users" to "service_role";

grant truncate on table "public"."users" to "service_role";

grant update on table "public"."users" to "service_role";

grant delete on table "public"."vehicles" to "anon";

grant insert on table "public"."vehicles" to "anon";

grant references on table "public"."vehicles" to "anon";

grant select on table "public"."vehicles" to "anon";

grant trigger on table "public"."vehicles" to "anon";

grant truncate on table "public"."vehicles" to "anon";

grant update on table "public"."vehicles" to "anon";

grant delete on table "public"."vehicles" to "authenticated";

grant insert on table "public"."vehicles" to "authenticated";

grant references on table "public"."vehicles" to "authenticated";

grant select on table "public"."vehicles" to "authenticated";

grant trigger on table "public"."vehicles" to "authenticated";

grant truncate on table "public"."vehicles" to "authenticated";

grant update on table "public"."vehicles" to "authenticated";

grant delete on table "public"."vehicles" to "service_role";

grant insert on table "public"."vehicles" to "service_role";

grant references on table "public"."vehicles" to "service_role";

grant select on table "public"."vehicles" to "service_role";

grant trigger on table "public"."vehicles" to "service_role";

grant truncate on table "public"."vehicles" to "service_role";

grant update on table "public"."vehicles" to "service_role";


