CREATE TABLE public.friends (
                                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                                sender_id BIGINT NOT NULL,
                                receiver_id BIGINT NOT NULL,

                                status VARCHAR(20) NOT NULL,
                                created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL,
                                updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL,

                                CONSTRAINT fk_friends_sender
                                    FOREIGN KEY (sender_id)
                                        REFERENCES public.users(id)
                                        ON DELETE CASCADE,

                                CONSTRAINT fk_friends_receiver
                                    FOREIGN KEY (receiver_id)
                                        REFERENCES public.users(id)
                                        ON DELETE CASCADE,

                                CONSTRAINT friends_status_check
                                    CHECK (status IN ('PENDING', 'ACCEPTED', 'DECLINED', 'BLOCKED')),

                                CONSTRAINT no_self_friend
                                    CHECK (sender_id <> receiver_id)
);

CREATE UNIQUE INDEX uq_friends_pair
    ON public.friends (sender_id, receiver_id);

CREATE INDEX ix_friends_sender
    ON public.friends (sender_id);

CREATE INDEX ix_friends_receiver
    ON public.friends (receiver_id);

CREATE INDEX ix_friends_status
    ON public.friends (status);