package campus.ride.entities;

import jakarta.persistence.*;
import java.time.LocalDateTime;

@Entity
@Table(name = "messages", indexes = {
        @Index(name = "ix_messages_sender_id", columnList = "sender_id"),
        @Index(name = "ix_messages_receiver_id", columnList = "receiver_id"),
        @Index(name = "ix_messages_conversation_id", columnList = "conversation_id"),
        @Index(name = "ix_messages_sent_at", columnList = "sent_at"),
        @Index(name = "ix_messages_drive_id", columnList = "drive_id")
})
public class Message {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "sender_id", nullable = false)
    private User sender;

    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "receiver_id", nullable = false)
    private User receiver;

    @Column(nullable = false, columnDefinition = "text")
    private String content;

    @Column(name = "sent_at", nullable = false, insertable = false, updatable = false, columnDefinition = "timestamp DEFAULT now()")
    private LocalDateTime sentAt;

    @Column(name = "is_read_by_sender", nullable = false)
    private Boolean isReadBySender = true; // Sender has "read" their own message by default

    @Column(name = "is_read_by_receiver", nullable = false)
    private Boolean isReadByReceiver = false;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "drive_id")
    private Drive drive;

    // Database-generated column: includes drive_id when present
    // Format: userId1_userId2 (private) or userId1_userId2_driveId (drive-related)
    @Column(name = "conversation_id", insertable = false, updatable = false)
    private String conversationId;

    protected Message() {
    }

    /**
     * Constructor for private messages (no drive association).
     */
    public Message(User sender, User receiver, String content) {
        this.sender = sender;
        this.receiver = receiver;
        this.content = content;
        this.isReadBySender = true; // Sender has "read" their own message
        this.isReadByReceiver = false;
        // conversationId is generated by database
    }

    /**
     * Constructor for drive-related messages.
     */
    public Message(User sender, User receiver, String content, Drive drive) {
        this.sender = sender;
        this.receiver = receiver;
        this.content = content;
        this.isReadBySender = true; // Sender has "read" their own message
        this.isReadByReceiver = false;
        this.drive = drive;
        // conversationId is generated by database (includes drive_id)
    }

    // Getters and Setters
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public User getSender() {
        return sender;
    }

    public void setSender(User sender) {
        this.sender = sender;
    }

    public User getReceiver() {
        return receiver;
    }

    public void setReceiver(User receiver) {
        this.receiver = receiver;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public LocalDateTime getSentAt() {
        return sentAt;
    }

    public void setSentAt(LocalDateTime sentAt) {
        this.sentAt = sentAt;
    }

    public Boolean getIsReadBySender() {
        return isReadBySender;
    }

    public void setIsReadBySender(Boolean isReadBySender) {
        this.isReadBySender = isReadBySender;
    }

    public Boolean getIsReadByReceiver() {
        return isReadByReceiver;
    }

    public void setIsReadByReceiver(Boolean isReadByReceiver) {
        this.isReadByReceiver = isReadByReceiver;
    }

    public Drive getDrive() {
        return drive;
    }

    public void setDrive(Drive drive) {
        this.drive = drive;
    }

    public String getConversationId() {
        return conversationId;
    }

    public void setConversationId(String conversationId) {
        this.conversationId = conversationId;
    }

    /**
     * Generates conversation ID for private messages (no drive).
     * Format: min(senderId, receiverId)_max(senderId, receiverId)
     */
    public static String generateConversationId(Long userId1, Long userId2) {
        Long minId = Math.min(userId1, userId2);
        Long maxId = Math.max(userId1, userId2);
        return minId + "_" + maxId;
    }

    /**
     * Generates conversation ID for drive-related messages.
     * Format: min(senderId, receiverId)_max(senderId, receiverId)_driveId
     */
    public static String generateConversationId(Long userId1, Long userId2, Long driveId) {
        Long minId = Math.min(userId1, userId2);
        Long maxId = Math.max(userId1, userId2);
        return minId + "_" + maxId + "_" + driveId;
    }
}
